PACKAGE_NAME="tenstorrent"
PACKAGE_VERSION="2.9.0"

BUILT_MODULE_NAME[0]="tenstorrent"
DEST_MODULE_LOCATION[0]="/kernel/extra"

# Custom vfio-pci variant driver, built in the vfio/ subdirectory.
BUILT_MODULE_NAME[1]="tenstorrent_vfio_pci"
BUILT_MODULE_LOCATION[1]="vfio"
DEST_MODULE_LOCATION[1]="/kernel/extra"

AUTOINSTALL="yes"

POST_INSTALL="./dkms-post-install"
